// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {result_model} from '../models';
import {main} from '../models';

export function GetRedisKeyData(arg1:string,arg2:string):Promise<void>;

export function GetScanRedisKey(arg1:string,arg2:number):Promise<result_model.RedisScanResult>;

export function GetSlotList():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;
