// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRedisKeyData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetRedisKeyData'](arg1, arg2, arg3, arg4);
}

export function GetScanRedisKey(arg1, arg2) {
  return window['go']['main']['App']['GetScanRedisKey'](arg1, arg2);
}

export function GetSlotList() {
  return window['go']['main']['App']['GetSlotList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}
